# Meta Classifier
Detect images generated using Meta AI. 

## Setup 

In [7]:
import torch
import os
import sys
import tqdm
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.utils import save_image
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler


import utils_img
import utils

sys.path.append('src')
from loss.loss_provider import LossProvider

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:32"


In [2]:
import gc 

def clear_memory():
    '''
    Delete unused tensors on GPU to reduce OOM issues. 
    '''
    try:
        del msg_extractor
    except: 
        pass
    try: 
        del img
    except:
        pass
    try: 
        del imgs
    except:
        pass
    try: 
        del targets
    except:
        pass
    gc.collect()
    torch.cuda.empty_cache()

clear_memory()

## Load Data

In [3]:
img_size = 256

# augment training set with some transformations 
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(img_size),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(degrees=180),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize(img_size),
    transforms.CenterCrop(img_size),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
    ])


In [5]:
from torch.utils.data import DataLoader, Subset
from torchvision.datasets.folder import default_loader
from torch.nn.utils.rnn import pad_sequence
import numpy as np 

batch_size = 4
train_dir = "data/meta/train"
train_size = 4770
val_dir = "data/meta/val"
val_size = 596

class ImageFolder:
    """An image folder dataset intended for supervised learning."""

    def __init__(self, path, transform=None, loader=default_loader):
        self.samples = [x for x in utils.get_image_paths(path) if not "aug" in x]
        self.loader = loader
        self.transform = transform

    def __getitem__(self, idx: int):
        """
        Returns the image with its corresponding label. Images are 
        labeled 0 if the image is not watermarked, else 1. 
        """
        assert 0 <= idx < len(self)
        path = self.samples[idx]
        img = self.loader(path)
        label = 0 if "orig" in path else 1
        if self.transform:
            img = self.transform(img)
        return img, label

    def __len__(self):
        return len(self.samples)


def get_dataloader(data_dir, transform, batch_size=128, num_imgs=None, shuffle=False, num_workers=4):
    """ Get dataloader for the images in the data_dir. """
    dataset = ImageFolder(data_dir, transform=transform)
    if num_imgs is not None:
        dataset = Subset(dataset, np.random.choice(len(dataset), num_imgs, replace=False))
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers, pin_memory=True, drop_last=False, collate_fn=None)


train_loader = get_dataloader(train_dir, train_transform, batch_size, num_imgs=train_size, shuffle=True)

# can try validate with image augmentations (train_transform) or without (val_transform)
val_loader = get_dataloader(val_dir, train_transform, 2, num_imgs=val_size, shuffle=True)


## Create Model 
Create a model by finetuning a 64-bit stable signature watermark extractor. Watermark extractor was trained for 300 epochs with the following command:

`torchrun --nproc_per_node=8 main.py --local_rank 0 --val_dir /home/test2017/ --train_dir /home/train2017/ --output_dir output64 --eval_freq 5   --img_size 256 --num_bits 64  --batch_size 16 --epochs 300   --scheduler CosineLRScheduler,lr_min=1e-6,t_initial=300,warmup_lr_init=1e-6,warmup_t=5  --optimizer Lamb,lr=2e-2   --p_color_jitter 0.0 --p_blur 0.0 --p_rot 0.0 --p_crop 1.0 --p_res 1.0 --p_jpeg 1.0   --scaling_w 0.3 --scale_channels False --attenuation none   --loss_w_type bce --loss_margin 1 
`

Watermark extractor was then whitened to ensure that the output bits more independent and well distributed (refer to stable signature paper). A whitened extractor was generated by running the finetune_ldm_decoder.py code once.

`python finetune_ldm_decoder.py --train_dir data/train --val_dir data/val --batch_size 1 --output_dir key0 --seed 0`


In [28]:
msg_extractor = torch.jit.load("hidden/runpod/checkpoint299_whit.pth").to("cpu")

model = nn.Sequential(
    nn.Sequential(*(list(msg_extractor.children())[:-1])),
    nn.Dropout(p=0.1),
    nn.Linear(in_features=64, out_features=1)
)

for param in model.parameters():
    param.requires_grad = True

optimizer = optim.Adam(model.parameters(), lr=0.001)

model

Sequential(
  (0): Sequential(
    (0): RecursiveScriptModule(
      original_name=HiddenDecoder
      (layers): RecursiveScriptModule(
        original_name=Sequential
        (0): RecursiveScriptModule(
          original_name=ConvBNRelu
          (layers): RecursiveScriptModule(
            original_name=Sequential
            (0): RecursiveScriptModule(original_name=Conv2d)
            (1): RecursiveScriptModule(original_name=BatchNorm2d)
            (2): RecursiveScriptModule(original_name=GELU)
          )
        )
        (1): RecursiveScriptModule(
          original_name=ConvBNRelu
          (layers): RecursiveScriptModule(
            original_name=Sequential
            (0): RecursiveScriptModule(original_name=Conv2d)
            (1): RecursiveScriptModule(original_name=BatchNorm2d)
            (2): RecursiveScriptModule(original_name=GELU)
          )
        )
        (2): RecursiveScriptModule(
          original_name=ConvBNRelu
          (layers): RecursiveScriptModule(

## Train Model 

In [53]:
def load_ckp(checkpoint_fpath, model, optimizer):
    checkpoint = torch.load(checkpoint_fpath)
    model.load_state_dict(checkpoint['state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer'])
    return model, optimizer, checkpoint['epoch']

def save_ckp(state, checkpoint_name):
    torch.save(state, checkpoint_name)


model, optimizer, start_epoch = load_ckp("models/meta/checkpoint010.pth", model, optimizer)

In [54]:
start_epoch

10

In [46]:
from sklearn.metrics import confusion_matrix

def train(model, data_loader, dataset_size, criterion, optimizer, scheduler, epoch):
    """
    Train model using the data_loader for 1 epoch. Prints out a confusion matrix,
    loss, and accuracy every 100 steps and at the end of the epoch.
    """
    model.train()
    pred_len = 0
    y_pred = []
    y_true = []
    test_correct = 0

    running_loss = 0.0
    # Iterate over data.
    for step, data in enumerate(tqdm.tqdm(data_loader)):
        clear_memory()
        inputs, labels = data
        inputs = inputs.to(device, dtype=torch.float)
        labels = labels.to(device, dtype=torch.float)
        optimizer.zero_grad()

        with torch.set_grad_enabled(True):
            outputs = model(inputs)
            targets = labels.unsqueeze(1)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            preds = torch.sigmoid(outputs).round().cpu().detach().numpy().squeeze()
            y_pred.extend(preds)
            labels = labels.cpu().numpy()
            y_true.extend(labels)
            test_correct += int((preds == labels).sum())
            pred_len += preds.size
            if step%100 == 0:
                print(f'Step: {step}, Loss:  {loss.item():.4f}, Acc: {test_correct/pred_len}')
                cf_matrix = confusion_matrix(y_true, y_pred)
                print(cf_matrix)

        running_loss += loss.item() * inputs.size(0)
    epoch_loss = running_loss / dataset_size
    print(f'Epoch: {epoch}, Loss: {epoch_loss:.4f}, Acc: {test_correct/pred_len}')
    cf_matrix = confusion_matrix(y_true, y_pred)
    print(cf_matrix)
    scheduler.step()
    return model 
    
def validate(model, data_loader, dataset_size, criterion):
    """
    Validates model using the data_loader. Prints out a confusion matrix,
    loss, and accuracy every 100 steps and at the end.
    """
    model.eval()
    pred_len = 0
    y_pred = []
    y_true = []
    test_correct = 0

    running_loss = 0.0
    # Iterate over data.
    for step, d in enumerate(tqdm.tqdm(data_loader)):
        clear_memory()
        inputs, labels = d
        inputs = inputs.to(device, dtype=torch.float)
        labels = labels.to(device, dtype=torch.float)
        with torch.no_grad():
            outputs = model(inputs)
            targets = labels.unsqueeze(1)
            loss = criterion(outputs, targets)
            preds = torch.sigmoid(outputs).round().cpu().detach().numpy().squeeze()
            y_pred.extend(preds)
            labels = labels.cpu().numpy()
            y_true.extend(labels)
            test_correct += int((preds == labels).sum())
            pred_len += preds.size
            if step%100 == 0:
                print(f'Step: {step}, Loss:  {loss.item():.4f}, Acc: {test_correct/pred_len}')
                cf_matrix = confusion_matrix(y_true, y_pred)
                print(cf_matrix)

        running_loss += loss.item() * inputs.size(0)
    epoch_loss = running_loss / dataset_size
    print(f'Val Loss: {epoch_loss:.4f}, Val Acc: {test_correct/pred_len}')
    cf_matrix = confusion_matrix(y_true, y_pred)
    print(cf_matrix)


def train_model(model, train_loader, train_size, val_loader, val_size, criterion, optimizer, scheduler, num_epochs):
    """
    Runs train and validate for num_epochs. 
    """
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)
        model = train(model, train_loader, train_size, criterion, optimizer, scheduler, epoch)
        clear_memory()
        validate(model, val_loader, val_size, criterion)
        if epoch%2 == 0:
            print(f"saving checkpoint...")
            checkpoint = {
                'epoch': epoch + 1,
                'state_dict': model.state_dict(),
                'optimizer': optimizer.state_dict()
            }
            save_ckp(checkpoint, f"models/meta/checkpoint{epoch:03}.pth")

    return model  


In [47]:
model = model.to(device)
criterion = nn.BCEWithLogitsLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)
lr_sch = lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

model = train_model(model, train_loader, train_size, val_loader, val_size, criterion, optimizer, lr_sch, 10)


Epoch 0/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:27,  2.10it/s]

Step: 0, Loss:  0.1607, Acc: 1.0
[[1 0]
 [0 3]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:26<04:51,  3.75it/s]

Step: 100, Loss:  0.0913, Acc: 0.8762376237623762
[[177  23]
 [ 27 177]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:53<04:24,  3.75it/s]

Step: 200, Loss:  0.0844, Acc: 0.8855721393034826
[[367  45]
 [ 47 345]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:19<03:58,  3.74it/s]

Step: 300, Loss:  0.0786, Acc: 0.8895348837209303
[[550  65]
 [ 68 521]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:46<03:31,  3.74it/s]

Step: 400, Loss:  0.0318, Acc: 0.89214463840399
[[743  87]
 [ 86 688]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:12<03:06,  3.72it/s]

Step: 500, Loss:  0.1404, Acc: 0.8962075848303394
[[945 105]
 [103 851]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:39<02:38,  3.73it/s]

Step: 600, Loss:  0.0412, Acc: 0.89891846921797
[[1133  118]
 [ 125 1028]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:06<02:12,  3.70it/s]

Step: 700, Loss:  0.2203, Acc: 0.9026390870185449
[[1312  134]
 [ 139 1219]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:33<01:45,  3.70it/s]

Step: 800, Loss:  0.8519, Acc: 0.9054307116104869
[[1508  147]
 [ 156 1393]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [03:59<01:18,  3.70it/s]

Step: 900, Loss:  0.8704, Acc: 0.9031631520532741
[[1674  167]
 [ 182 1581]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:26<00:51,  3.70it/s]

Step: 1000, Loss:  0.1702, Acc: 0.9040959040959041
[[1860  183]
 [ 201 1760]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:53<00:24,  3.71it/s]

Step: 1100, Loss:  0.0953, Acc: 0.9064486830154405
[[2025  197]
 [ 215 1967]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:17<00:00,  3.75it/s]


Epoch: 0, Loss: 0.2455, Acc: 0.9052410901467505
[[2185  215]
 [ 237 2133]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:40,  7.37it/s]

Step: 0, Loss:  0.0131, Acc: 1.0
[[1 0]
 [0 1]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.69it/s]

Step: 100, Loss:  0.0634, Acc: 0.9504950495049505
[[106   6]
 [  4  86]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:08, 10.61it/s]

Step: 200, Loss:  0.0456, Acc: 0.945273631840796
[[192   8]
 [ 14 188]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.59it/s]


Val Loss: 0.1303, Val Acc: 0.9496644295302014
[[289  11]
 [ 19 277]]
saving checkpoint...
Epoch 1/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:07,  2.18it/s]

Step: 0, Loss:  0.8301, Acc: 0.75
[[1 0]
 [1 2]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:51,  3.74it/s]

Step: 100, Loss:  0.4181, Acc: 0.900990099009901
[[201  18]
 [ 22 163]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:53<04:29,  3.69it/s]

Step: 200, Loss:  0.4647, Acc: 0.9216417910447762
[[405  29]
 [ 34 336]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:20<04:00,  3.71it/s]

Step: 300, Loss:  0.1994, Acc: 0.915282392026578
[[605  47]
 [ 55 497]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:47<03:32,  3.73it/s]

Step: 400, Loss:  0.6387, Acc: 0.9152119700748129
[[789  63]
 [ 73 679]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:14<03:06,  3.71it/s]

Step: 500, Loss:  0.0822, Acc: 0.9186626746506986
[[983  78]
 [ 85 858]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:41<02:39,  3.72it/s]

Step: 600, Loss:  0.0005, Acc: 0.920549084858569
[[1162   95]
 [  96 1051]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:07<02:13,  3.67it/s]

Step: 700, Loss:  0.0053, Acc: 0.9226105563480742
[[1342  110]
 [ 107 1245]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:34<01:45,  3.70it/s]

Step: 800, Loss:  0.1068, Acc: 0.9210362047440699
[[1518  130]
 [ 123 1433]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:01<01:18,  3.72it/s]

Step: 900, Loss:  0.0544, Acc: 0.9223085460599334
[[1699  142]
 [ 138 1625]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:28<00:52,  3.67it/s]

Step: 1000, Loss:  0.1062, Acc: 0.9210789210789211
[[1878  160]
 [ 156 1810]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:55<00:24,  3.68it/s]

Step: 1100, Loss:  0.0449, Acc: 0.9187102633969119
[[2049  180]
 [ 178 1997]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:20<00:00,  3.73it/s]


Epoch: 1, Loss: 0.1981, Acc: 0.9207547169811321
[[2211  189]
 [ 189 2181]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:42,  6.87it/s]

Step: 0, Loss:  0.0070, Acc: 1.0
[[2]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.46it/s]

Step: 100, Loss:  0.3701, Acc: 0.9603960396039604
[[104   1]
 [  7  90]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:08, 10.63it/s]

Step: 200, Loss:  0.0659, Acc: 0.9527363184079602
[[205   4]
 [ 15 178]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.54it/s]


Val Loss: 0.1269, Val Acc: 0.9513422818791947
[[295   5]
 [ 24 272]]
Epoch 2/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<08:44,  2.27it/s]

Step: 0, Loss:  0.3280, Acc: 0.75
[[2 0]
 [1 1]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:52,  3.73it/s]

Step: 100, Loss:  0.0536, Acc: 0.9529702970297029
[[218   9]
 [ 10 167]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:27,  3.70it/s]

Step: 200, Loss:  0.0614, Acc: 0.9402985074626866
[[412  22]
 [ 26 344]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:05,  3.63it/s]

Step: 300, Loss:  0.0596, Acc: 0.9435215946843853
[[609  31]
 [ 37 527]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:34,  3.69it/s]

Step: 400, Loss:  0.2267, Acc: 0.940149625935162
[[774  48]
 [ 48 734]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.68it/s]

Step: 500, Loss:  0.1377, Acc: 0.935129740518962
[[944  67]
 [ 63 930]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:41,  3.67it/s]

Step: 600, Loss:  0.0600, Acc: 0.9330282861896838
[[1145   82]
 [  79 1098]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:14,  3.67it/s]

Step: 700, Loss:  0.1537, Acc: 0.9290299572039943
[[1338  100]
 [  99 1267]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:46,  3.69it/s]

Step: 800, Loss:  0.1973, Acc: 0.9275905118601748
[[1526  117]
 [ 115 1446]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:02<01:19,  3.67it/s]

Step: 900, Loss:  0.1502, Acc: 0.9275804661487237
[[1691  130]
 [ 131 1652]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.66it/s]

Step: 1000, Loss:  0.5204, Acc: 0.9270729270729271
[[1879  144]
 [ 148 1833]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:56<00:25,  3.64it/s]

Step: 1100, Loss:  0.0071, Acc: 0.9282470481380564
[[2072  156]
 [ 160 2016]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:21<00:00,  3.71it/s]


Epoch: 2, Loss: 0.1881, Acc: 0.9283018867924528
[[2232  168]
 [ 174 2196]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:39,  7.38it/s]

Step: 0, Loss:  0.0024, Acc: 1.0
[[1 0]
 [0 1]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.47it/s]

Step: 100, Loss:  0.0089, Acc: 0.9603960396039604
[[99  2]
 [ 6 95]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:08, 10.57it/s]

Step: 200, Loss:  0.0481, Acc: 0.9651741293532339
[[196   2]
 [ 12 192]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.45it/s]


Val Loss: 0.0972, Val Acc: 0.964765100671141
[[297   3]
 [ 18 278]]
saving checkpoint...
Epoch 3/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:27,  2.10it/s]

Step: 0, Loss:  0.0615, Acc: 1.0
[[1 0]
 [0 3]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:53,  3.72it/s]

Step: 100, Loss:  0.5483, Acc: 0.9183168316831684
[[175  15]
 [ 18 196]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:26,  3.72it/s]

Step: 200, Loss:  0.0275, Acc: 0.9241293532338308
[[375  27]
 [ 34 368]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:02,  3.68it/s]

Step: 300, Loss:  0.0185, Acc: 0.9294019933554817
[[548  40]
 [ 45 571]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:34,  3.69it/s]

Step: 400, Loss:  0.1210, Acc: 0.9307980049875312
[[731  51]
 [ 60 762]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.70it/s]

Step: 500, Loss:  2.2628, Acc: 0.935129740518962
[[932  60]
 [ 70 942]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:40,  3.68it/s]

Step: 600, Loss:  0.0936, Acc: 0.9309484193011647
[[1108   81]
 [  85 1130]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:13,  3.69it/s]

Step: 700, Loss:  0.0462, Acc: 0.9308131241084165
[[1308   93]
 [ 101 1302]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:35<01:46,  3.69it/s]

Step: 800, Loss:  0.0600, Acc: 0.9335205992509363
[[1490  102]
 [ 111 1501]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:02<01:19,  3.67it/s]

Step: 900, Loss:  0.6277, Acc: 0.9325749167591565
[[1688  118]
 [ 125 1673]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:29<00:52,  3.67it/s]

Step: 1000, Loss:  0.1683, Acc: 0.9338161838161838
[[1886  129]
 [ 136 1853]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.67it/s]

Step: 1100, Loss:  0.0067, Acc: 0.9330154405086285
[[2089  141]
 [ 154 2020]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:21<00:00,  3.71it/s]


Epoch: 3, Loss: 0.1753, Acc: 0.9316561844863732
[[2243  157]
 [ 169 2201]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:40,  7.37it/s]

Step: 0, Loss:  0.0277, Acc: 1.0
[[2]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:10<00:18, 10.54it/s]

Step: 100, Loss:  0.3406, Acc: 0.9158415841584159
[[88  0]
 [17 97]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:09, 10.51it/s]

Step: 200, Loss:  0.1655, Acc: 0.9129353233830846
[[191   0]
 [ 35 176]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.41it/s]


Val Loss: 0.2099, Val Acc: 0.9060402684563759
[[297   3]
 [ 53 243]]
Epoch 4/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<08:31,  2.33it/s]

Step: 0, Loss:  0.0085, Acc: 1.0
[[3 0]
 [0 1]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:54,  3.71it/s]

Step: 100, Loss:  0.0099, Acc: 0.9381188118811881
[[179  11]
 [ 14 200]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:29,  3.68it/s]

Step: 200, Loss:  0.0012, Acc: 0.9514925373134329
[[388  17]
 [ 22 377]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:02,  3.67it/s]

Step: 300, Loss:  0.0012, Acc: 0.9534883720930233
[[578  26]
 [ 30 570]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:33,  3.71it/s]

Step: 400, Loss:  0.7428, Acc: 0.9532418952618454
[[783  36]
 [ 39 746]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.69it/s]

Step: 500, Loss:  0.0088, Acc: 0.9520958083832335
[[988  45]
 [ 51 920]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:40,  3.68it/s]

Step: 600, Loss:  0.0148, Acc: 0.9492512479201332
[[1172   60]
 [  62 1110]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:12,  3.70it/s]

Step: 700, Loss:  0.0459, Acc: 0.9443651925820257
[[1342   76]
 [  80 1306]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:35<01:46,  3.68it/s]

Step: 800, Loss:  0.0231, Acc: 0.9472534332084894
[[1524   82]
 [  87 1511]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:02<01:19,  3.69it/s]

Step: 900, Loss:  0.0183, Acc: 0.9461709211986682
[[1719   92]
 [ 102 1691]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.64it/s]

Step: 1000, Loss:  0.0633, Acc: 0.9478021978021978
[[1920   98]
 [ 111 1875]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.67it/s]

Step: 1100, Loss:  0.7345, Acc: 0.9423251589464123
[[2100  122]
 [ 132 2050]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:21<00:00,  3.71it/s]


Epoch: 4, Loss: 0.1542, Acc: 0.9417190775681342
[[2263  137]
 [ 141 2229]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:42,  6.91it/s]

Step: 0, Loss:  0.0890, Acc: 1.0
[[2]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.52it/s]

Step: 100, Loss:  0.1590, Acc: 0.9207920792079208
[[88 13]
 [ 3 98]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:08, 10.59it/s]

Step: 200, Loss:  0.2513, Acc: 0.927860696517413
[[180  24]
 [  5 193]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.51it/s]


Val Loss: 0.1522, Val Acc: 0.9395973154362416
[[269  31]
 [  5 291]]
saving checkpoint...
Epoch 5/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<08:55,  2.23it/s]

Step: 0, Loss:  0.0559, Acc: 1.0
[[2 0]
 [0 2]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:54,  3.71it/s]

Step: 100, Loss:  0.1146, Acc: 0.943069306930693
[[194  12]
 [ 11 187]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:28,  3.70it/s]

Step: 200, Loss:  0.0489, Acc: 0.9378109452736318
[[388  26]
 [ 24 366]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:00,  3.70it/s]

Step: 300, Loss:  1.0949, Acc: 0.9410299003322259
[[577  39]
 [ 32 556]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:34,  3.70it/s]

Step: 400, Loss:  0.4034, Acc: 0.9395261845386533
[[777  51]
 [ 46 730]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.68it/s]

Step: 500, Loss:  0.1036, Acc: 0.9421157684630739
[[961  60]
 [ 56 927]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:41,  3.66it/s]

Step: 600, Loss:  0.2181, Acc: 0.9450915141430949
[[1143   69]
 [  63 1129]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:13,  3.70it/s]

Step: 700, Loss:  1.4115, Acc: 0.9432952924393724
[[1321   80]
 [  79 1324]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:47,  3.65it/s]

Step: 800, Loss:  0.0039, Acc: 0.9441323345817728
[[1515   89]
 [  90 1510]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:03<01:19,  3.67it/s]

Step: 900, Loss:  0.4061, Acc: 0.9436736958934517
[[1708  102]
 [ 101 1693]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.68it/s]

Step: 1000, Loss:  0.0201, Acc: 0.9425574425574426
[[1897  113]
 [ 117 1877]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.68it/s]

Step: 1100, Loss:  0.0107, Acc: 0.9432334241598547
[[2079  124]
 [ 126 2075]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:21<00:00,  3.71it/s]


Epoch: 5, Loss: 0.1414, Acc: 0.9436058700209644
[[2267  133]
 [ 136 2234]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:42,  6.92it/s]

Step: 0, Loss:  0.0062, Acc: 1.0
[[2]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.49it/s]

Step: 100, Loss:  0.0063, Acc: 0.9801980198019802
[[103   1]
 [  3  95]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:09, 10.45it/s]

Step: 200, Loss:  0.0000, Acc: 0.9701492537313433
[[198   4]
 [  8 192]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.44it/s]


Val Loss: 0.0729, Val Acc: 0.9714765100671141
[[294   6]
 [ 11 285]]
Epoch 6/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<08:34,  2.32it/s]

Step: 0, Loss:  0.0096, Acc: 1.0
[[3 0]
 [0 1]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:53,  3.73it/s]

Step: 100, Loss:  0.0034, Acc: 0.9554455445544554
[[193   8]
 [ 10 193]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:27,  3.71it/s]

Step: 200, Loss:  1.1182, Acc: 0.945273631840796
[[397  23]
 [ 21 363]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:00,  3.71it/s]

Step: 300, Loss:  0.0135, Acc: 0.9493355481727574
[[590  33]
 [ 28 553]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:33,  3.72it/s]

Step: 400, Loss:  0.0136, Acc: 0.9507481296758105
[[781  41]
 [ 38 744]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.69it/s]

Step: 500, Loss:  0.0044, Acc: 0.9481037924151696
[[971  54]
 [ 50 929]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:40,  3.68it/s]

Step: 600, Loss:  0.0006, Acc: 0.947171381031614
[[1165   63]
 [  64 1112]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:13,  3.68it/s]

Step: 700, Loss:  0.2312, Acc: 0.9472182596291013
[[1367   74]
 [  74 1289]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:45,  3.71it/s]

Step: 800, Loss:  0.3570, Acc: 0.949438202247191
[[1552   81]
 [  81 1490]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:03<01:19,  3.68it/s]

Step: 900, Loss:  0.7669, Acc: 0.9495005549389567
[[1732   92]
 [  90 1690]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.65it/s]

Step: 1000, Loss:  0.0021, Acc: 0.951048951048951
[[1918  100]
 [  96 1890]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.64it/s]

Step: 1100, Loss:  0.5102, Acc: 0.9507266121707538
[[2098  111]
 [ 106 2089]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:21<00:00,  3.71it/s]


Epoch: 6, Loss: 0.1285, Acc: 0.9515723270440252
[[2283  117]
 [ 114 2256]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:41,  7.15it/s]

Step: 0, Loss:  0.0003, Acc: 1.0
[[1 0]
 [0 1]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.60it/s]

Step: 100, Loss:  0.0188, Acc: 0.995049504950495
[[109   0]
 [  1  92]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:09, 10.54it/s]

Step: 200, Loss:  0.0017, Acc: 0.9925373134328358
[[203   0]
 [  3 196]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.49it/s]


Val Loss: 0.0514, Val Acc: 0.9848993288590604
[[299   1]
 [  8 288]]
saving checkpoint...
Epoch 7/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:20,  2.13it/s]

Step: 0, Loss:  0.0040, Acc: 1.0
[[2 0]
 [0 2]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:57,  3.67it/s]

Step: 100, Loss:  0.0064, Acc: 0.9579207920792079
[[201   8]
 [  9 186]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:28,  3.69it/s]

Step: 200, Loss:  0.2214, Acc: 0.9552238805970149
[[409  19]
 [ 17 359]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:00,  3.70it/s]

Step: 300, Loss:  0.0010, Acc: 0.957641196013289
[[602  25]
 [ 26 551]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:34,  3.69it/s]

Step: 400, Loss:  0.0038, Acc: 0.9557356608478803
[[771  36]
 [ 35 762]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:09,  3.66it/s]

Step: 500, Loss:  0.0663, Acc: 0.9595808383233533
[[974  43]
 [ 38 949]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:41,  3.66it/s]

Step: 600, Loss:  0.7524, Acc: 0.9579866888519135
[[1168   53]
 [  48 1135]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:14,  3.66it/s]

Step: 700, Loss:  0.0083, Acc: 0.9579172610556348
[[1368   60]
 [  58 1318]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:46,  3.68it/s]

Step: 800, Loss:  0.0029, Acc: 0.9584893882646691
[[1561   67]
 [  66 1510]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:03<01:19,  3.67it/s]

Step: 900, Loss:  0.0312, Acc: 0.959211986681465
[[1750   72]
 [  75 1707]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.65it/s]

Step: 1000, Loss:  0.0046, Acc: 0.9590409590409591
[[1954   81]
 [  83 1886]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.67it/s]

Step: 1100, Loss:  0.0272, Acc: 0.9591280653950953
[[2139   90]
 [  90 2085]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:22<00:00,  3.70it/s]


Epoch: 7, Loss: 0.1079, Acc: 0.959958071278826
[[2304   96]
 [  95 2275]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:42,  6.96it/s]

Step: 0, Loss:  0.2110, Acc: 1.0
[[2]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:10<00:18, 10.47it/s]

Step: 100, Loss:  0.0040, Acc: 0.9752475247524752
[[109   5]
 [  0  88]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:09, 10.40it/s]

Step: 200, Loss:  0.0000, Acc: 0.9825870646766169
[[206   7]
 [  0 189]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.42it/s]


Val Loss: 0.0541, Val Acc: 0.9848993288590604
[[292   8]
 [  1 295]]
Epoch 8/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:29,  2.09it/s]

Step: 0, Loss:  0.0028, Acc: 1.0
[[2 0]
 [0 2]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:55,  3.70it/s]

Step: 100, Loss:  0.0080, Acc: 0.9603960396039604
[[193   9]
 [  7 195]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:28,  3.69it/s]

Step: 200, Loss:  0.0027, Acc: 0.9539800995024875
[[386  21]
 [ 16 381]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<04:01,  3.69it/s]

Step: 300, Loss:  0.0151, Acc: 0.9518272425249169
[[589  32]
 [ 26 557]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:34,  3.69it/s]

Step: 400, Loss:  0.2773, Acc: 0.9526184538653366
[[776  39]
 [ 37 752]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.70it/s]

Step: 500, Loss:  0.0101, Acc: 0.9565868263473054
[[966  46]
 [ 41 951]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:40,  3.69it/s]

Step: 600, Loss:  0.0024, Acc: 0.9559068219633944
[[1149   55]
 [  51 1149]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:14,  3.67it/s]

Step: 700, Loss:  0.0089, Acc: 0.9518544935805991
[[1345   68]
 [  67 1324]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:46,  3.69it/s]

Step: 800, Loss:  0.0191, Acc: 0.9547440699126092
[[1557   73]
 [  72 1502]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:03<01:20,  3.65it/s]

Step: 900, Loss:  0.0175, Acc: 0.9575471698113207
[[1765   78]
 [  75 1686]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:53,  3.62it/s]

Step: 1000, Loss:  0.3674, Acc: 0.9572927072927073
[[1941   88]
 [  83 1892]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.66it/s]

Step: 1100, Loss:  0.0025, Acc: 0.9577656675749319
[[2133   98]
 [  88 2085]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:22<00:00,  3.70it/s]


Epoch: 8, Loss: 0.1195, Acc: 0.9568134171907757
[[2293  107]
 [  99 2271]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:40,  7.28it/s]

Step: 0, Loss:  0.0319, Acc: 1.0
[[1 0]
 [0 1]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.50it/s]

Step: 100, Loss:  0.0001, Acc: 0.9455445544554455
[[ 86   9]
 [  2 105]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:09, 10.52it/s]

Step: 200, Loss:  0.0005, Acc: 0.9477611940298507
[[184  14]
 [  7 197]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.50it/s]


Val Loss: 0.1730, Val Acc: 0.947986577181208
[[280  20]
 [ 11 285]]
saving checkpoint...
Epoch 9/9
----------


  0%|▏                                                                                                                                                                     | 1/1193 [00:00<09:54,  2.01it/s]

Step: 0, Loss:  0.2908, Acc: 0.75
[[0 0]
 [1 3]]


  8%|█████████████▉                                                                                                                                                      | 101/1193 [00:27<04:55,  3.70it/s]

Step: 100, Loss:  0.0171, Acc: 0.9381188118811881
[[196  13]
 [ 12 183]]


 17%|███████████████████████████▋                                                                                                                                        | 201/1193 [00:54<04:27,  3.70it/s]

Step: 200, Loss:  0.0057, Acc: 0.9552238805970149
[[396  19]
 [ 17 372]]


 25%|█████████████████████████████████████████▍                                                                                                                          | 301/1193 [01:21<03:59,  3.72it/s]

Step: 300, Loss:  0.0977, Acc: 0.9509966777408638
[[596  32]
 [ 27 549]]


 34%|███████████████████████████████████████████████████████                                                                                                             | 401/1193 [01:48<03:35,  3.68it/s]

Step: 400, Loss:  0.0094, Acc: 0.9544887780548629
[[810  39]
 [ 34 721]]


 42%|████████████████████████████████████████████████████████████████████▊                                                                                               | 501/1193 [02:15<03:07,  3.70it/s]

Step: 500, Loss:  0.0314, Acc: 0.9580838323353293
[[993  43]
 [ 41 927]]


 50%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 601/1193 [02:42<02:41,  3.65it/s]

Step: 600, Loss:  0.0150, Acc: 0.9604825291181365
[[1182   49]
 [  46 1127]]


 59%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                   | 701/1193 [03:09<02:13,  3.67it/s]

Step: 700, Loss:  0.0109, Acc: 0.9604136947218259
[[1374   58]
 [  53 1319]]


 67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 801/1193 [03:36<01:46,  3.67it/s]

Step: 800, Loss:  0.0116, Acc: 0.9597378277153558
[[1579   65]
 [  64 1496]]


 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 901/1193 [04:03<01:19,  3.66it/s]

Step: 900, Loss:  1.4638, Acc: 0.9583795782463929
[[1754   75]
 [  75 1700]]


 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1001/1193 [04:30<00:52,  3.69it/s]

Step: 1000, Loss:  0.0059, Acc: 0.9575424575424576
[[1945   87]
 [  83 1889]]


 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1101/1193 [04:57<00:25,  3.66it/s]

Step: 1100, Loss:  0.3319, Acc: 0.9582198001816531
[[2132   92]
 [  92 2088]]


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1193/1193 [05:22<00:00,  3.70it/s]


Epoch: 9, Loss: 0.1152, Acc: 0.9580712788259959
[[2301   99]
 [ 101 2269]]


  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:37,  7.78it/s]

Step: 0, Loss:  0.0013, Acc: 1.0
[[2]]


 34%|████████████████████████████████████████████████████████▍                                                                                                            | 102/298 [00:09<00:18, 10.51it/s]

Step: 100, Loss:  0.0003, Acc: 0.9603960396039604
[[ 92   5]
 [  3 102]]


 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                     | 202/298 [00:19<00:09, 10.56it/s]

Step: 200, Loss:  0.0016, Acc: 0.9477611940298507
[[180  17]
 [  4 201]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:28<00:00, 10.50it/s]

Val Loss: 0.0887, Val Acc: 0.9614093959731543
[[281  19]
 [  4 292]]


### Save model

In [52]:
print(f"saving checkpoint...")
checkpoint = {
    'epoch': 10,
    'state_dict': model.state_dict(),
    'optimizer': optimizer.state_dict()
}
save_ckp(checkpoint, f"models/meta/checkpoint010.pth")


saving checkpoint...


In [63]:
#jit_model = torch.jit.script(model)
#torch.jit.save(jit_model, "models/meta_classifier.pt")

In [55]:
validate(model, val_loader, val_size, criterion)

  1%|█▋                                                                                                                                                                     | 3/298 [00:00<00:39,  7.49it/s]

Step: 0, Loss:  0.0188, Acc: 1.0
[[1 0]
 [0 1]]


 35%|█████████████████████████████████████████████████████████                                                                                                            | 103/298 [00:09<00:18, 10.70it/s]

Step: 100, Loss:  0.0388, Acc: 0.9801980198019802
[[99  2]
 [ 2 99]]


 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                    | 203/298 [00:19<00:08, 10.78it/s]

Step: 200, Loss:  0.0038, Acc: 0.972636815920398
[[191   8]
 [  3 200]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 298/298 [00:27<00:00, 10.69it/s]

Val Loss: 0.0940, Val Acc: 0.9664429530201343
[[284  16]
 [  4 292]]


## Validation

Code to test on a single image or a test directory. The output 1 indicates that the image is generated by Meta AI, 0 otherwise. 

In [56]:
model, optimizer, start_epoch = load_ckp("models/meta/checkpoint010.pth", model, optimizer)

In [58]:
from PIL import Image

with torch.no_grad():
    #img_path = "/ssd/watermarks/stable_signature/data/meta-aug/331_jpeg_80_w.png"
    img_path = "/ssd/watermarks/stable_signature/meta.jpeg"
    img = Image.open(img_path)
    img = val_transform(img).unsqueeze(0).to(device)
    model.eval()
    output = model(img)
pred = torch.sigmoid(output).round().cpu().detach().numpy().squeeze()
pred

array(1., dtype=float32)

In [59]:
test_dir = "test"
# test with no image augmentations
test_loader = get_dataloader(test_dir, val_transform, 2, num_imgs=500, shuffle=True)
validate(model, test_loader, val_size, criterion)

  1%|██                                                                                                                                                                     | 3/250 [00:00<00:34,  7.11it/s]

Step: 0, Loss:  0.0014, Acc: 1.0
[[2]]


 41%|███████████████████████████████████████████████████████████████████▉                                                                                                 | 103/250 [00:09<00:13, 10.81it/s]

Step: 100, Loss:  0.0131, Acc: 0.9900990099009901
[[ 97   0]
 [  2 103]]


 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 203/250 [00:19<00:04, 10.75it/s]

Step: 200, Loss:  0.0265, Acc: 0.9950248756218906
[[200   0]
 [  2 200]]


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [00:23<00:00, 10.67it/s]

Val Loss: 0.0410, Val Acc: 0.99
[[250   2]
 [  3 245]]
